- .travis.yml
- Dockerfile.tests
- Makefile
- README.md
- container_ci_suite/api.py
- container_ci_suite/utils.py
- requirements.sh
- requirements.txt
- tests/test_utils.py
Add support for testing container-ci-suite in container.
> Add first test suite

- tests/conftest.py
- tests/spellbook.py
- tests/test_utils.py
Add tests for NPM mirror and CA_FILE_MOUNT
> Add tests for npm_variables and ca_filemount

- Dockerfile.tests
- Makefile
- README.md
- container_ci_suite/api.py
- container_ci_suite/container.py
- container_ci_suite/utils.py
- tests/conftest.py
- tests/data/test-app/README.md
- tests/data/test-app/iisnode.yml
- tests/data/test-app/package.json
- tests/data/test-app/server.js
- tests/data/test-app/web.config
- tests/test_api.py
- tests/test_utils.py
> Add Dockerfile.test with proper image

- Dockerfile.tests
- Makefile
- container_ci_suite/api.py
- container_ci_suite/container.py
- tests/conftest.py
- tests/test_api.py
> First try with s2i_build_as_df

- Dockerfile.tests
- README.md
- container_ci_suite/git.py
- requirements.txt
- tests/test_git.py
- tox.ini
In sclorg repositories we need to create a repo.
This pull request allows it.
Closes #11
> Fixes #11: Add support for adding git repos

- .github/workflows/pre-commit-tests.yml
> Add pre-commit-test suite

- .github/workflows/pre-commit-tests.yml
> Fix pre-commit GA

- README.md
- container_ci_suite/helm.py
- container_ci_suite/utils.py
- tests/data/oc_get_pod_status.json
- tests/data/postgresql_imagestreams.json
> First draft for helm charts

- container_ci_suite/helm.py
- tests/test_helm.py
Proper handling random number generator.
> Add more numbers

- container_ci_suite/helm.py
> More outputs

- container_ci_suite/helm.py
Add support for list of strings to check from `helm test` command output.
> Support list of strings to check

- container_ci_suite/helm.py
> Let's remove namespace assert

- container_ci_suite/helm.py
- tests/test_helm.py
> Add installation check

- container_ci_suite/helm.py
> Fix deployment status

- container_ci_suite/helm.py
- requirements.txt
- tox.ini
> Add support for curl by requests

- .github/workflows/python-tests.yml
> Switch to main branch

- container_ci_suite/helm.py
- container_ci_suite/openshift.py
> Fix helm namespace

- Dockerfile.tests
- README.md
- container_ci_suite/openshift.py
- tests/conftest.py
- tests/data/oc_create_ruby_rhel_json.json
- tests/data/oc_get_is_ruby.json
- tests/data/oc_new_app_ruby.json
- tests/data/oc_process_rails_postgresql.json
- tests/test_openshift.py
This pull request adds support for testing Ex repositories in OpenShift.
> First draft for testing Ex prepositories

- README.md
- container_ci_suite/helm.py
- container_ci_suite/openshift.py
- setup.py
- tests/data/oc_get_routes_cakephp.json
> Refactor Helm chart for s2i

- container_ci_suite/helm.py
- tests/conftest.py
- tests/data/Chart.yaml
- tests/test_helm.py
> Catch traceback in case of helm test failed

- container_ci_suite/helm.py
> In case pod is running break the cycle

- container_ci_suite/helm.py
- container_ci_suite/logger.py
- container_ci_suite/openshift.py
> Get rid off gargage calling

- container_ci_suite/helm.py
> Fix curl test suite

- container_ci_suite/helm.py
> Only one pod is allowed.

- container_ci_suite/helm.py
- setup.py
> Fix multiple pods

- .github/workflows/python-tests.yml
- tox.ini
> Let's support tests also in Python 311

- container_ci_suite/helm.py
> Let's separate count for pod and build_pod

- container_ci_suite/openshift.py
- container_ci_suite/utils.py
> Add support for command_app tests inside cluster

- container_ci_suite/openshift.py
> Fix calling get status command

- container_ci_suite/openshift.py
> Add possibility to specify branch

- container_ci_suite/openshift.py
> Detect failure and do not use json format for pring status

- container_ci_suite/utils.py
> Add support for local files

- tests/test_openshift.py
> Fix test suite

- Dockerfile.tests
- Makefile
- container_ci_suite/helm.py
- container_ci_suite/imagestreams.py
- container_ci_suite/openshift.py
- container_ci_suite/utils.py
- requirements.txt
- tests/data/oc_default_route.json
- tests/test_utils.py
Add support for imagestreams as well
> Add support for testing s2i images

- container_ci_suite/container.py
- container_ci_suite/openshift.py
- container_ci_suite/utils.py
- setup.py
- tests/conftest.py
- tests/data/oc_build_pod_finished.json
- tests/data/oc_build_pod_not_finished.json
- tests/data/oc_get_svc.json
- tests/data/oc_get_svc_empty.json
- tests/data/oc_is_pod_running.json
- tests/test_openshift.py
> Support imagestream_quickstart

- .github/workflows/python-tests.yml
- tox.ini
> Add support for testing also in Python 3.12 environment

- .github/workflows/pypi-publish.yml
> New PYpI token

- container_ci_suite/openshift.py
- setup.py
> Fix typo in functions

- container_ci_suite/openshift.py
- setup.py
> Fix names in function

- container_ci_suite/imagestreams.py
- container_ci_suite/openshift.py
> Add service_name to deploy_s2i_app

- container_ci_suite/container.py
> Fix checking docker image

- container_ci_suite/utils.py
> Fix download function

- container_ci_suite/openshift.py
- setup.py
> Add image_stream_template

- container_ci_suite/openshift.py
> Do not use -p in case of empty OPenShift args

- container_ci_suite/openshift.py
- setup.py
> Fix printing

- container_ci_suite/openshift.py
- setup.py
> Fix generation openshift args

- container_ci_suite/openshift.py
> Fix count of tests

- container_ci_suite/utils.py
- setup.py
> Enable print run_command on request

- container_ci_suite/utils.py
- tests/test_utils.py
> Use VERSION instead of SINGLE_VERSION, like on whole org

- container_ci_suite/openshift.py
- container_ci_suite/utils.py
- setup.py
- tests/test_utils.py
This pull request implements testing sclorg container on Shared cluster.
Currently it is triggered by variable `shared_cluster` in OpenShiftAPi initialization.
> Add support for shared cluster

- container_ci_suite/helm.py
- container_ci_suite/openshift.py
- container_ci_suite/openshift_ops.py
- container_ci_suite/utils.py
- tests/test_helm.py
- tests/test_openshift.py
- tests/test_openshift_ops.py
> Shared cluster

- container_ci_suite/openshift.py
> Fix function get_raw_url

- container_ci_suite/openshift.py
> Add more debug information about project deletion and creation

- container_ci_suite/openshift.py
> Fix tentat egress rules.

- container_ci_suite/helm.py
- container_ci_suite/openshift_ops.py
- container_ci_suite/utils.py
- setup.py
- tests/test_helm.py
> Add support for testing remote Helm Charts repositories

- README.md
- container_ci_suite/api.py
- container_ci_suite/container_engine.py
- container_ci_suite/openshift.py
- container_ci_suite/utils.py
- tests/test_openshift.py
> Update README.md and add more texts

- container_ci_suite/helm.py
- container_ci_suite/openshift.py
- container_ci_suite/openshift_ops.py
- container_ci_suite/utils.py
- setup.py
- tests/test_utils.py
This pull request allows to test Helm Charts in shared cluster.
> Let's use shared cluster on Helm Charts

- container_ci_suite/helm.py
remote is not used at all, but some test still use it.
> Let's preserve backwards compatibility

- container_ci_suite/utils.py
> In rules definition is missing ','

- container_ci_suite/engines/openshift.py
- container_ci_suite/openshift.py
This pull request allows to login to internal or shared cluster.
> Allow to login to internal or shared cluster

- container_ci_suite/helm.py
Mostlyl it could be caused by OpenShift error like:
* Operation cannot be fulfilled on clusterresourcequotas.quota.openshift.io "core-services-ocp--general": the object has been modified; please apply your changes to the latest version and try again
> In case of installation failed, then try it one more time.

- container_ci_suite/engines/openshift.py
- container_ci_suite/helm.py
case testing on shared cluster is suppressed
> Fix for getting local cluster for Helm Chart testing in case testing on shared cluster is suppressed

- container_ci_suite/helm.py
- container_ci_suite/openshift.py
> In case of shared_cluster is not used, then

- container_ci_suite/helm.py
- container_ci_suite/utils.py
> Use share_cluster_values properly

- container_ci_suite/engines/openshift.py
Add more debug output in case of pod is not running after specific time for the other analizes.
> Add more debug output in case pod is not running

- container_ci_suite/openshift.py
- setup.py
On SharedCluster sometimes building took a long time
> Add timeout option to 'template_deployed' function.

- container_ci_suite/openshift.py
- container_ci_suite/utils.py
- tests/test_openshift.py
- tests/test_utils.py
> Fix openshift s2i

- container_ci_suite/openshift.py
- container_ci_suite/utils.py
This pull request adds support for tenantnamespace creation,
Sometimes, tenantnamespace took a bit more time then expected and therefore we need to check if project really exists.
> Support delay for tenantnamespace creation and applying egress rules

- container_ci_suite/openshift.py
Easay fix. Do not apply limits on project at all.
> Disable limits for now. It makes a troubles with deployment

- container_ci_suite/engines/openshift.py
- container_ci_suite/openshift.py
> Show debug infos in case even it failed

- container_ci_suite/container_lib.py
- container_ci_suite/engines/podman_wrapper.py
> Add insecure to test response

- container_ci_suite/container_lib.py
- setup.py
> Fix npm calling and add mount_ca_file to `podman run`

- container_ci_suite/container_lib.py
> Build curl arguments before for cycle
